import type { InspirationData } from '@/pages/Home/Creator/InspirationPage/CreatorInspirationCardSection';

export const creatorInspirations: InspirationData[] = [
  {
    id: '1',
    title: 'Retro-themed pub poster for young adults',
    description: 'Create eye-catching pub posters with vintage aesthetics',
    image: '',
    category: 'POSTER',
    earnAmount: 10,
    timeLeft: { days: 1, unit: 'DAY' },
    badges: [{ text: 'New', tone: 'info' }],
  },
  {
    id: '2',
    title: 'Eco-friendly product packaging design',
    description: 'Design sustainable packaging solutions for eco-conscious brands',
    image: '',
    category: 'PACKAGE',
    earnAmount: 8,
    timeLeft: { days: 3, unit: 'DAYS' },
    badges: [{ text: 'New', tone: 'info' }],
  },
  {
    id: '3',
    title: 'Modern restaurant menu layout',
    description: 'Create sophisticated menu designs for upscale restaurants',
    image: '',
    category: 'MENU',
    earnAmount: 12,
    trendData: { value: '150K', percentage: 45 },
    badges: [{ text: 'New', tone: 'info' }],
  },
  {
    id: '4',
    title: 'Fitness app social media graphics',
    description: 'Design engaging social media content for fitness applications',
    image: '',
    category: 'SOCIAL',
    trendData: { value: '200K', percentage: 30 },
  },
  {
    id: '5',
    title: 'Tech startup brand identity',
    description: 'Develop comprehensive brand identity for technology startups',
    image: '',
    category: 'BRAND',
    trendData: { value: '180K', percentage: 25 },
  },
  {
    id: '6',
    title: 'Wedding invitation suite design',
    description: 'Create elegant invitation suites for wedding celebrations',
    image: '',
    category: 'INVITE',
    earnAmount: 15,
    timeLeft: { days: 2, unit: 'DAYS' },
  },
];
