import type { TextStyleItem } from '@/pages/home/Brand/components/BrandComponents/TextStyleList';

// Sample text styles data
// Add more text styles here as needed
export const textStyles: TextStyleItem[] = [
  {
    id: 'title',
    type: 'title',
    name: 'Title',
    fontFamily: 'Inter, -apple-system, sans-serif',
    fontSize: 48,
    fontWeight: 700,
    fontStyle: 'normal',
    isDefault: false,
  },
  {
    id: 'subtitle',
    type: 'subtitle',
    name: 'Subtitle',
    fontFamily: 'Inter, -apple-system, sans-serif',
    fontSize: 36,
    fontWeight: 400,
    fontStyle: 'normal',
    isDefault: false,
  },
  {
    id: 'heading',
    type: 'heading',
    name: 'Heading',
    fontFamily: 'Inter, -apple-system, sans-serif',
    fontSize: 32,
    fontWeight: 700,
    fontStyle: 'normal',
    isDefault: false,
  },
  {
    id: 'subheading',
    type: 'subheading',
    name: 'Subheading',
    fontFamily: 'Inter, -apple-system, sans-serif',
    fontSize: 24,
    fontWeight: 600,
    fontStyle: 'normal',
    isDefault: false,
  },
  {
    id: 'section-header',
    type: 'section-header',
    name: 'Section header',
    fontFamily: 'Inter, -apple-system, sans-serif',
    fontSize: 20,
    fontWeight: 600,
    fontStyle: 'normal',
    isDefault: false,
  },
  {
    id: 'body',
    type: 'body',
    name: 'Body',
    fontFamily: 'Inter, -apple-system, sans-serif',
    fontSize: 16,
    fontWeight: 400,
    fontStyle: 'normal',
    isDefault: false,
  },
  {
    id: 'quote',
    type: 'quote',
    name: 'Quote',
    fontFamily: 'Georgia, serif',
    fontSize: 18,
    fontWeight: 400,
    fontStyle: 'italic',
    isDefault: false,
  },
  {
    id: 'caption',
    type: 'caption',
    name: 'Caption',
    fontFamily: 'Inter, -apple-system, sans-serif',
    fontSize: 14,
    fontWeight: 400,
    fontStyle: 'normal',
    isDefault: false,
  },
];
